version: "3.6"

services:
  price:
    build:
      context: .
    image: k830206/signoz-price:latest
    ports:
    - "65020:3000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4318
      NODE_ENV: production
